# Generated by Django 6.1 on 2026-08-23 17:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_code', models.CharField(help_text='Human-readable identifier, e.g. SEN-001.', max_length=50, unique=True)),
                ('location', models.CharField(help_text='Physical location description.', max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=15)),
                ('installed_at', models.DateField(help_text='Date the sensor was physically deployed.')),
            ],
            options={
                'ordering': ['sensor_code'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm25', models.FloatField(help_text='PM2.5 concentration in µg/m³.', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('pm10', models.FloatField(help_text='PM10 concentration in µg/m³.', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('temperature', models.FloatField(help_text='Temperature in °C.')),
                ('humidity', models.FloatField(help_text='Relative humidity in %.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.sensor')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sensor', 'timestamp'], name='idx_reading_sensor_ts')],
            },
        ),
    ]
