# Generated by Django 6.1 on 2026-08-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Decimal latitude of the sensor installation point.', null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Decimal longitude of the sensor installation point.', null=True),
        ),
    ]
