# Generated by Django 6.1 on 2026-09-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_sensor_lat_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='data_source',
            field=models.CharField(choices=[('simulated', 'Simulated Demo Data'), ('live', 'Live WAQI Feed')], default='simulated', help_text="Origin of telemetry data ('simulated' or 'live').", max_length=20),
        ),
    ]
