# Generated by Django 6.1 on 2026-09-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('service', 'Service')], default='user', help_text='Admins manage system, users view, service accounts ingest telemetry.', max_length=10),
        ),
    ]
