# Generated by Django 6.1 on 2026-08-23 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(choices=[('pm25', 'PM2.5 (µg/m³)'), ('pm10', 'PM10 (µg/m³)'), ('temperature', 'Temperature (°C)'), ('humidity', 'Humidity (%)')], help_text='The air-quality parameter this threshold applies to.', max_length=50, unique=True)),
                ('warning_limit', models.FloatField(help_text='Value above which a LOW/MEDIUM severity alert is raised.')),
                ('critical_limit', models.FloatField(help_text='Value above which a HIGH severity alert is raised.')),
            ],
            options={
                'ordering': ['parameter'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('threshold', 'Threshold'), ('ml', 'ML Anomaly')], max_length=20)),
                ('parameter', models.CharField(help_text="Which measurement triggered the alert (e.g. 'pm25').", max_length=50)),
                ('value', models.FloatField(help_text='The measurement value at alert creation time.')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved')], default='open', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reading', models.ForeignKey(blank=True, help_text='The specific reading that triggered this alert (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='sensors.sensorreading')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='sensors.sensor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='idx_alert_status_created')],
            },
        ),
    ]
